version: '3.8'

services:
  db:
    image: postgres:15
    container_name: django_blog_db
    environment:
      POSTGRES_DB: djangoblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./blogapp
      dockerfile: Dockerfile
    container_name: django_blog_app
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - ./blogapp:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=djangoblog
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
    restart: unless-stopped

volumes:
  postgres_data:
