# Generated by Django 5.2.7 on 2025-10-19 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARN", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("api", "API Request"),
                            ("error", "Error"),
                            ("migration", "Migration"),
                            ("audit", "Audit"),
                            ("auth", "Authentication"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the user associated with this log entry",
                        null=True,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the object associated with this log entry",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data related to the log entry",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier for the request that generated this log",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the client", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of the client",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Log",
                "verbose_name_plural": "System Logs",
                "db_table": "system_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["level", "timestamp"],
                        name="system_logs_level_36b166_idx",
                    ),
                    models.Index(
                        fields=["category", "timestamp"],
                        name="system_logs_categor_322359_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="system_logs_user_id_942324_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="system_logs_request_abf88a_idx"
                    ),
                ],
            },
        ),
    ]
